// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqkoemhfpaivmmjyodxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa29lbWhmcGFpdm1tanlvZHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjM3NjcsImV4cCI6MjA1NTk5OTc2N30.J620fMxZ5XI1S-jUagUIg_4C0PcOydkRuuGcvYNt8S8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);